version: 0.2

run-as: root

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - aws configure set aws_access_key_id ${AK}
      - aws configure set aws_secret_access_key ${SAK}
      - aws configure set default.region ${REGION}      
      - npm install -g serverless
      - npm install
  build:
    commands:    #cada --paramname paramValue, se para al archivo serverless.yml como  ${opt:paramName}
      - serverless deploy --param="client=aos" --param="projectName=boilerplate" --param="type=api" --param="environment=${ENV}" --stage=${STAGE} --param="region=${REGION}" --param="memorySize=128" --param="timeout=20" --param="logRetentionInDays=3" --param="region=${REGION}" --param="cognitoUserpoolId=${CGUSERPOOLID}" --param="cognitoAK=${CGAK}" --param="cognitoSAK=${CGSAK}" --param="cognitoClientId=${CGCID}"
cache:
  paths:
    - node_modules